---
- hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP and dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php-fpm
        - php-mysql

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions on WordPress directory
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

    - name: Configure Nginx for WordPress
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html/wordpress;
              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
        dest: /etc/nginx/sites-available/wordpress
        owner: root
        group: root
        mode: '0644'

    - name: Enable WordPress site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted